name: Debug Test
on: 
  push:
    branches: 
      - '*'

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
    env:
      budi: ${{github.run_id}}
    steps:
    - name: Output Run ID
      run: echo $budi
    - name: Output Run Number
      run: echo ${{ github.run_number }}
    - name: Output Run Attempt
      run: echo ${{ github.run_attempt }}
