name: Debug Test
on: 
  push:
    branches: 
      - '*'

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
    steps:
    - name: Output Run ID
      run: echo ${{ github.run_id }}
    - name: Output Run Number
      run: echo ${{ github.run_number }}
    - name: Output Run Attempt
      run: echo ${{ github.run_attempt }}
